theme: jekyll-theme-minimal
title: My awesome title
author: yagao95
email: fangtao6793@163.com
description: > # this means to ignore newlines until "baseurl:"
( à° àµ à°  )ï¾‰ğŸ‚
å«¦å¨¥
# social links
twitter_username: abc-twitter-handle
github_username:  abc-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
